addons:
  apt:
    packages:
      - lmodern
      - pgf
      - texlive-lang-english
      - texlive-latex-base
      - latex-xcolor
      - texlive-xetex
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-math-extra

branches:
  except:
    - /^v\d{4}\-\d{2}\-\d{2}(-\S*)?$/

before_script:
  - export TZ=America/Chicago
script:
  - mkdir build
  - xelatex -output-directory=build resume.tex
before_deploy:
  - git config --local user.name "Chris McKnight"
  - git config --local user.email "cmckni3@gmail.com"
  - export TAG_DATE="v$(date +'%Y-%m-%d')"
  - export TAG="$TAG_DATE-$(git log --format=%h -1 $TRAVIS_COMMIT)"
  - git tag "$TAG" "$TRAVIS_COMMIT"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: "$TAG_DATE"
  file:
    - ./build/resume.pdf
  skip_cleanup: true
  on:
    branch: master
