language: node_js
node_js:
  - 12
os: linux

addons:
  apt:
    packages:
      - lmodern
      - pgf
      - texlive-lang-english
      - texlive-latex-base
      - latex-xcolor
      - texlive-xetex
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-math-extra

branches:
  except:
    - /^v\d{4}\-\d{2}\-\d{2}(-\S*)?$/

before_script:
  - export TZ=America/Chicago
script:
  - mkdir build
  - xelatex -output-directory=build Christopher-McKnight-resume.tex
before_deploy:
  - git config --local user.name "Chris McKnight"
  - git config --local user.email "cmckni3@gmail.com"
  - export RELEASE_TITLE="$(date +'%Y-%m')"
  - export TAG="v$(date +'%Y-%m-%d')-$(git log --format=%h -1 $TRAVIS_COMMIT)"
  - git tag "$TAG" "$TRAVIS_COMMIT"
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  edge: true
  name: '$RELEASE_TITLE'
  file:
    - ./build/Christopher-McKnight-resume.pdf
  on:
    branch: master
