addons:
  apt:
    packages:
      - lmodern
      - pgf
      - texlive-lang-english
      - texlive-latex-base
      - latex-xcolor
      - texlive-xetex
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-math-extra
script:
  - mkdir build
  - xelatex -output-directory=build resume.tex
before_deploy:
  - export TZ=America/Chicago
  - git config --local user.name "Chris McKnight"
  - git config --local user.email "cmckni3@gmail.com"
  - git tag "$(date +'%Y-%m-%d')-$TRAVIS_COMMIT" $TRAVIS_COMMIT
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ./build/resume.pdf
  skip_cleanup: true
  on:
    branch: master
