name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/cli@master
    - uses: scarhand/actions-ruby@master
    - name: install dpl
      run: gem install dpl
    - name: dpl info
      run: dpl --provider=releases
    - name: build docker image
      run: docker build -f support/docker/Dockerfile -t cmckni3/resume .
    - name: run docker container
      run: docker run -v $(pwd):/data cmckni3/resume xelatex
