name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/cli@master
    - name: build docker image
      run: docker build -f support/docker/Dockerfile -t cmckni3/resume .
    - name: run docker container
      run: docker run -v .:/data cmckni3/resume xelatex
