name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    # TODO: Convert to use Docker
    - name: Install latex
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install -y -qq --no-install-suggests --no-install-recommends \
          git \
          ca-certificates \
          lmodern \
          pgf \
          texlive-lang-english \
          texlive-latex-base \
          latex-xcolor \
          texlive-xetex \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-latex-extra \
          texlive-math-extra
    - name: Create directory
      run: mkdir build
    - name: Build resume
      run: xelatex -output-directory=build Christopher-McKnight-resume.tex
