name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') || !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v1
      - name: build docker image
        run: docker build -f support/docker/Dockerfile -t cmckni3/resume .
      - name: run docker container
        run: docker run -v $(pwd):/data cmckni3/resume xelatex
